### ISSUE TITLE
Add support for `react-native` 0.76

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#2131]
### Version

0.76

### Discussion

https://github.com/orgs/reactwg/projects/13/views/2

### Blocking issues

- [x] https://github.com/facebook/react-native/issues/45461
- [x] https://github.com/microsoft/react-native-test-app/pull/2196
- [x] https://github.com/microsoft/react-native-test-app/pull/2216
- [x] https://github.com/microsoft/react-native-test-app/pull/2221
- [x] https://github.com/facebook/react-native/pull/46453
- [x] https://github.com/microsoft/react-native-test-app/pull/2223
- [x] https://github.com/microsoft/react-native-windows/issues/13914
- [x] https://github.com/microsoft/react-native-test-app/pull/2269
- [x] https://github.com/microsoft/react-native-test-app/pull/2275
- [x] https://github.com/microsoft/react-native-test-app/pull/2301
- [ ] https://github.com/facebook/react-native/pull/47304
- [ ] https://github.com/facebook/react-native/pull/47308
- [x] https://github.com/facebook/react-native/issues/47309
- [x] https://github.com/facebook/react-native/pull/47310

### What platforms will be updated?

- [X] Android
- [X] iOS
- [ ] macOS
- [X] visionOS
- [X] Windows

### Tasks

- [x] Verify that the Gradle version used is the same or higher ([see context](https://github.com/microsoft/react-native-test-app/pull/1935))
- [ ] Ensure React Native Gradle Plugin autolinking code are in sync ([see context](https://github.com/microsoft/react-native-test-app/pull/2075))
- [x] Ensure feature flags are in sync ([see context](https://github.com/microsoft/rnx-kit/pull/3196/files))

### End-to-end tests

- [x] Android - Fabric: disabled
- [x] Android - Fabric: **enabled**
- [x] iOS - Fabric: disabled / Hermes: disabled
- [x] iOS - Fabric: disabled / Hermes: **enabled**
- [x] iOS - Fabric: **enabled** / Hermes: disabled
- [x] iOS - Fabric: **enabled** / Hermes: **enabled**
- [ ] macOS
- [x] visionOS
- [x] Windows - NuGet: disabled
- [x] Windows - NuGet: **enabled**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
