### ISSUE TITLE
Add support for `react-native` 0.77

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#2313]
### Version

0.77

### Discussion

tbd

### Blocking issues

- [x] https://github.com/microsoft/react-native-test-app/pull/2314
- [x] https://github.com/microsoft/react-native-test-app/pull/2324
- [x] https://github.com/microsoft/rnx-kit/pull/3430
- [x] https://github.com/microsoft/rnx-kit/pull/3434
- [x] https://github.com/microsoft/rnx-kit/pull/3443

### What platforms will be updated?

- [x] Android
- [x] iOS
- [ ] macOS
- [ ] visionOS
- [ ] Windows

### Tasks

- [ ] Verify that the Gradle version used is the same or higher ([see context](https://github.com/microsoft/react-native-test-app/pull/1935))
- [ ] Ensure React Native Gradle Plugin autolinking code are in sync ([see context](https://github.com/microsoft/react-native-test-app/pull/2075))
- [x] Ensure feature flags are in sync ([see context](https://github.com/microsoft/rnx-kit/pull/3196/files))

### End-to-end tests

- [ ] Android - Fabric: disabled
- [ ] Android - Fabric: **enabled**
- [ ] iOS - Fabric: disabled / Hermes: disabled
- [ ] iOS - Fabric: disabled / Hermes: **enabled**
- [ ] iOS - Fabric: **enabled** / Hermes: disabled
- [ ] iOS - Fabric: **enabled** / Hermes: **enabled**
- [ ] macOS
- [ ] visionOS
- [ ] Windows - NuGet: disabled
- [ ] Windows - NuGet: **enabled**

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
