### ISSUE TITLE
Add support for React Native for macOS

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#54]
https://github.com/microsoft/react-native

Blocked by:
- [x] [Make macOS apps work using CocoaPods](https://github.com/microsoft/react-native/issues/215)
- [x] [Make modern autolinking work for macOS](https://github.com/microsoft/react-native/issues/220) (implemented in [Enable auto-linking of native modules](https://github.com/microsoft/react-native/pull/312))
- [ ] [Improve Metro support for out-of-tree platforms](https://github.com/react-native-community/discussions-and-proposals/issues/182)

Tasks:
- [ ] Add support for non-iOS platforms in `test_app.rb` (#86)
- [ ] Implement the test app itself (#87)
- [ ] Add macOS target to Plop template (#88)
- [ ] Update the [wiki](https://github.com/microsoft/react-native-test-app/wiki) and document platform specifics

**Comment by tido64** [comment]
Closed in favour of [macOS project](/microsoft/react-native-test-app/projects/2).
