### ISSUE TITLE
Add support for React Native for Windows

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#55]
https://microsoft.github.io/react-native-windows/

Blocked by:
- [ ] [Improve Metro support for out-of-tree platforms](https://github.com/react-native-community/discussions-and-proposals/issues/182)

Tasks:
- [ ] Implement Windows test app (#89)
- [ ] Add Windows target to Plop template (#90)
- [ ] Update the [wiki](https://github.com/microsoft/react-native-test-app/wiki) and document platform specifics

**Comment by tido64** [comment]
Closed in favour of [Windows project](/microsoft/react-native-test-app/projects/3).
