### ISSUE TITLE
Implement Windows test app

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#89]
#### Acceptance Criteria

- [x] Create skeleton app with React menu (#136)
  - Load From Embedded JS Bundle
  - Load From Dev Server
- [x] Implement loading of the [manifest](https://github.com/microsoft/react-native-test-app/wiki/Manifest-(app.json)) (#142)
  - [x] Populate the React menu with components from the manifest
- [x] Initialize React Native bridge on app startup (#166)
  - [x] Hook up `Load From Embedded JS Bundle`
  - [x] Hook up `Load From Dev Server`
  - [x] Implement launching a React component from the React menu
- [x] Figure out how to consume the test app via npm (#192)
  - [x] ¯\\_(ツ)_/¯
- [x] Add Windows target to CI (#202)
- [x] Add quick start instructions to README

#### Stretch Goals

- [x] Add unit tests (#202)
- [x] Move React menu to the title bar and center the app title, similar to how Visual Studio looks (#178)
  | | |
  |-|-|
  | Visual Studio | ![image](https://user-images.githubusercontent.com/4123478/87765173-c863ad00-c817-11ea-84cb-f9db03b48835.png) |
  | Visual Studio Code | ![image](https://user-images.githubusercontent.com/4123478/87765083-ad913880-c817-11ea-9858-9803c54c02d8.png) |
- [x] Add option to open the debug menu in React menu (#194):
  ![image](https://user-images.githubusercontent.com/4123478/89771132-21192380-db00-11ea-88a0-3abdec13e6e2.png)
- [x] Add keyboard accelerators to items in React menu (#194):
  ![image](https://user-images.githubusercontent.com/4123478/89823290-85b09e80-db51-11ea-8e53-f05238c4538c.png)
- ~~Make sure autolinking works (depends on https://github.com/microsoft/react-native-windows/issues/2853)~~

#### Non-Goals

- ARM (just making sure it builds is enough)
